// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: product.proto

package productclient

import (
	"context"

	"github.com/292292yang/go-zero-mall/product-rpc/product"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CheckStockReq     = product.CheckStockReq
	CheckStockResp    = product.CheckStockResp
	CreateProductReq  = product.CreateProductReq
	CreateProductResp = product.CreateProductResp
	DeductStockReq    = product.DeductStockReq
	DeductStockResp   = product.DeductStockResp
	GetProductReq     = product.GetProductReq
	GetProductResp    = product.GetProductResp
	ListProductReq    = product.ListProductReq
	ListProductResp   = product.ListProductResp
	ProductInfo       = product.ProductInfo

	Product interface {
		CreateProduct(ctx context.Context, in *CreateProductReq, opts ...grpc.CallOption) (*CreateProductResp, error)
		GetProduct(ctx context.Context, in *GetProductReq, opts ...grpc.CallOption) (*GetProductResp, error)
		ListProduct(ctx context.Context, in *ListProductReq, opts ...grpc.CallOption) (*ListProductResp, error)
		CheckStock(ctx context.Context, in *CheckStockReq, opts ...grpc.CallOption) (*CheckStockResp, error)
		DeductStock(ctx context.Context, in *DeductStockReq, opts ...grpc.CallOption) (*DeductStockResp, error)
	}

	defaultProduct struct {
		cli zrpc.Client
	}
)

func NewProduct(cli zrpc.Client) Product {
	return &defaultProduct{
		cli: cli,
	}
}

func (m *defaultProduct) CreateProduct(ctx context.Context, in *CreateProductReq, opts ...grpc.CallOption) (*CreateProductResp, error) {
	client := product.NewProductClient(m.cli.Conn())
	return client.CreateProduct(ctx, in, opts...)
}

func (m *defaultProduct) GetProduct(ctx context.Context, in *GetProductReq, opts ...grpc.CallOption) (*GetProductResp, error) {
	client := product.NewProductClient(m.cli.Conn())
	return client.GetProduct(ctx, in, opts...)
}

func (m *defaultProduct) ListProduct(ctx context.Context, in *ListProductReq, opts ...grpc.CallOption) (*ListProductResp, error) {
	client := product.NewProductClient(m.cli.Conn())
	return client.ListProduct(ctx, in, opts...)
}

func (m *defaultProduct) CheckStock(ctx context.Context, in *CheckStockReq, opts ...grpc.CallOption) (*CheckStockResp, error) {
	client := product.NewProductClient(m.cli.Conn())
	return client.CheckStock(ctx, in, opts...)
}

func (m *defaultProduct) DeductStock(ctx context.Context, in *DeductStockReq, opts ...grpc.CallOption) (*DeductStockResp, error) {
	client := product.NewProductClient(m.cli.Conn())
	return client.DeductStock(ctx, in, opts...)
}
