// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.4
// source: proto/product.proto

package product

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProductInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int64                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Price         int64                  `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`
	Stock         int64                  `protobuf:"varint,5,opt,name=stock,proto3" json:"stock,omitempty"`
	Status        int64                  `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductInfo) Reset() {
	*x = ProductInfo{}
	mi := &file_proto_product_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductInfo) ProtoMessage() {}

func (x *ProductInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductInfo.ProtoReflect.Descriptor instead.
func (*ProductInfo) Descriptor() ([]byte, []int) {
	return file_proto_product_proto_rawDescGZIP(), []int{0}
}

func (x *ProductInfo) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *ProductInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProductInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ProductInfo) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *ProductInfo) GetStock() int64 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *ProductInfo) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

type CreateProductReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Price         int64                  `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	Stock         int64                  `protobuf:"varint,4,opt,name=stock,proto3" json:"stock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProductReq) Reset() {
	*x = CreateProductReq{}
	mi := &file_proto_product_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductReq) ProtoMessage() {}

func (x *CreateProductReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductReq.ProtoReflect.Descriptor instead.
func (*CreateProductReq) Descriptor() ([]byte, []int) {
	return file_proto_product_proto_rawDescGZIP(), []int{1}
}

func (x *CreateProductReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateProductReq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateProductReq) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CreateProductReq) GetStock() int64 {
	if x != nil {
		return x.Stock
	}
	return 0
}

type CreateProductResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int64                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProductResp) Reset() {
	*x = CreateProductResp{}
	mi := &file_proto_product_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductResp) ProtoMessage() {}

func (x *CreateProductResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductResp.ProtoReflect.Descriptor instead.
func (*CreateProductResp) Descriptor() ([]byte, []int) {
	return file_proto_product_proto_rawDescGZIP(), []int{2}
}

func (x *CreateProductResp) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

type GetProductReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int64                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductReq) Reset() {
	*x = GetProductReq{}
	mi := &file_proto_product_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductReq) ProtoMessage() {}

func (x *GetProductReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductReq.ProtoReflect.Descriptor instead.
func (*GetProductReq) Descriptor() ([]byte, []int) {
	return file_proto_product_proto_rawDescGZIP(), []int{3}
}

func (x *GetProductReq) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

type GetProductResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       *ProductInfo           `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductResp) Reset() {
	*x = GetProductResp{}
	mi := &file_proto_product_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductResp) ProtoMessage() {}

func (x *GetProductResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductResp.ProtoReflect.Descriptor instead.
func (*GetProductResp) Descriptor() ([]byte, []int) {
	return file_proto_product_proto_rawDescGZIP(), []int{4}
}

func (x *GetProductResp) GetProduct() *ProductInfo {
	if x != nil {
		return x.Product
	}
	return nil
}

type ListProductReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keyword       string                 `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"`
	Page          int64                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int64                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductReq) Reset() {
	*x = ListProductReq{}
	mi := &file_proto_product_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductReq) ProtoMessage() {}

func (x *ListProductReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductReq.ProtoReflect.Descriptor instead.
func (*ListProductReq) Descriptor() ([]byte, []int) {
	return file_proto_product_proto_rawDescGZIP(), []int{5}
}

func (x *ListProductReq) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *ListProductReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListProductReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListProductResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*ProductInfo         `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductResp) Reset() {
	*x = ListProductResp{}
	mi := &file_proto_product_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductResp) ProtoMessage() {}

func (x *ListProductResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductResp.ProtoReflect.Descriptor instead.
func (*ListProductResp) Descriptor() ([]byte, []int) {
	return file_proto_product_proto_rawDescGZIP(), []int{6}
}

func (x *ListProductResp) GetList() []*ProductInfo {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *ListProductResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type CheckStockReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int64                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity      int64                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckStockReq) Reset() {
	*x = CheckStockReq{}
	mi := &file_proto_product_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckStockReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckStockReq) ProtoMessage() {}

func (x *CheckStockReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckStockReq.ProtoReflect.Descriptor instead.
func (*CheckStockReq) Descriptor() ([]byte, []int) {
	return file_proto_product_proto_rawDescGZIP(), []int{7}
}

func (x *CheckStockReq) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *CheckStockReq) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type CheckStockResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enough        bool                   `protobuf:"varint,1,opt,name=enough,proto3" json:"enough,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckStockResp) Reset() {
	*x = CheckStockResp{}
	mi := &file_proto_product_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckStockResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckStockResp) ProtoMessage() {}

func (x *CheckStockResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckStockResp.ProtoReflect.Descriptor instead.
func (*CheckStockResp) Descriptor() ([]byte, []int) {
	return file_proto_product_proto_rawDescGZIP(), []int{8}
}

func (x *CheckStockResp) GetEnough() bool {
	if x != nil {
		return x.Enough
	}
	return false
}

func (x *CheckStockResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DeductStockReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int64                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity      int64                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	RequestId     string                 `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeductStockReq) Reset() {
	*x = DeductStockReq{}
	mi := &file_proto_product_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeductStockReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeductStockReq) ProtoMessage() {}

func (x *DeductStockReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeductStockReq.ProtoReflect.Descriptor instead.
func (*DeductStockReq) Descriptor() ([]byte, []int) {
	return file_proto_product_proto_rawDescGZIP(), []int{9}
}

func (x *DeductStockReq) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *DeductStockReq) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *DeductStockReq) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type DeductStockResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeductStockResp) Reset() {
	*x = DeductStockResp{}
	mi := &file_proto_product_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeductStockResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeductStockResp) ProtoMessage() {}

func (x *DeductStockResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeductStockResp.ProtoReflect.Descriptor instead.
func (*DeductStockResp) Descriptor() ([]byte, []int) {
	return file_proto_product_proto_rawDescGZIP(), []int{10}
}

func (x *DeductStockResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_proto_product_proto protoreflect.FileDescriptor

const file_proto_product_proto_rawDesc = "" +
	"\n" +
	"\x13proto/product.proto\x12\aproduct\"\xa6\x01\n" +
	"\vProductInfo\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x03R\tproductId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x03R\x05price\x12\x14\n" +
	"\x05stock\x18\x05 \x01(\x03R\x05stock\x12\x16\n" +
	"\x06status\x18\x06 \x01(\x03R\x06status\"t\n" +
	"\x10CreateProductReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x03R\x05price\x12\x14\n" +
	"\x05stock\x18\x04 \x01(\x03R\x05stock\"2\n" +
	"\x11CreateProductResp\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x03R\tproductId\".\n" +
	"\rGetProductReq\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x03R\tproductId\"@\n" +
	"\x0eGetProductResp\x12.\n" +
	"\aproduct\x18\x01 \x01(\v2\x14.product.ProductInfoR\aproduct\"[\n" +
	"\x0eListProductReq\x12\x18\n" +
	"\akeyword\x18\x01 \x01(\tR\akeyword\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x03R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x03R\bpageSize\"Q\n" +
	"\x0fListProductResp\x12(\n" +
	"\x04list\x18\x01 \x03(\v2\x14.product.ProductInfoR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"J\n" +
	"\rCheckStockReq\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x03R\tproductId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x03R\bquantity\"B\n" +
	"\x0eCheckStockResp\x12\x16\n" +
	"\x06enough\x18\x01 \x01(\bR\x06enough\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"j\n" +
	"\x0eDeductStockReq\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x03R\tproductId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x03R\bquantity\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\tR\trequestId\"+\n" +
	"\x0fDeductStockResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xd3\x02\n" +
	"\aProduct\x12F\n" +
	"\rCreateProduct\x12\x19.product.CreateProductReq\x1a\x1a.product.CreateProductResp\x12=\n" +
	"\n" +
	"GetProduct\x12\x16.product.GetProductReq\x1a\x17.product.GetProductResp\x12@\n" +
	"\vListProduct\x12\x17.product.ListProductReq\x1a\x18.product.ListProductResp\x12=\n" +
	"\n" +
	"CheckStock\x12\x16.product.CheckStockReq\x1a\x17.product.CheckStockResp\x12@\n" +
	"\vDeductStock\x12\x17.product.DeductStockReq\x1a\x18.product.DeductStockRespB\vZ\t./productb\x06proto3"

var (
	file_proto_product_proto_rawDescOnce sync.Once
	file_proto_product_proto_rawDescData []byte
)

func file_proto_product_proto_rawDescGZIP() []byte {
	file_proto_product_proto_rawDescOnce.Do(func() {
		file_proto_product_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_product_proto_rawDesc), len(file_proto_product_proto_rawDesc)))
	})
	return file_proto_product_proto_rawDescData
}

var file_proto_product_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_product_proto_goTypes = []any{
	(*ProductInfo)(nil),       // 0: product.ProductInfo
	(*CreateProductReq)(nil),  // 1: product.CreateProductReq
	(*CreateProductResp)(nil), // 2: product.CreateProductResp
	(*GetProductReq)(nil),     // 3: product.GetProductReq
	(*GetProductResp)(nil),    // 4: product.GetProductResp
	(*ListProductReq)(nil),    // 5: product.ListProductReq
	(*ListProductResp)(nil),   // 6: product.ListProductResp
	(*CheckStockReq)(nil),     // 7: product.CheckStockReq
	(*CheckStockResp)(nil),    // 8: product.CheckStockResp
	(*DeductStockReq)(nil),    // 9: product.DeductStockReq
	(*DeductStockResp)(nil),   // 10: product.DeductStockResp
}
var file_proto_product_proto_depIdxs = []int32{
	0,  // 0: product.GetProductResp.product:type_name -> product.ProductInfo
	0,  // 1: product.ListProductResp.list:type_name -> product.ProductInfo
	1,  // 2: product.Product.CreateProduct:input_type -> product.CreateProductReq
	3,  // 3: product.Product.GetProduct:input_type -> product.GetProductReq
	5,  // 4: product.Product.ListProduct:input_type -> product.ListProductReq
	7,  // 5: product.Product.CheckStock:input_type -> product.CheckStockReq
	9,  // 6: product.Product.DeductStock:input_type -> product.DeductStockReq
	2,  // 7: product.Product.CreateProduct:output_type -> product.CreateProductResp
	4,  // 8: product.Product.GetProduct:output_type -> product.GetProductResp
	6,  // 9: product.Product.ListProduct:output_type -> product.ListProductResp
	8,  // 10: product.Product.CheckStock:output_type -> product.CheckStockResp
	10, // 11: product.Product.DeductStock:output_type -> product.DeductStockResp
	7,  // [7:12] is the sub-list for method output_type
	2,  // [2:7] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_proto_product_proto_init() }
func file_proto_product_proto_init() {
	if File_proto_product_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_product_proto_rawDesc), len(file_proto_product_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_product_proto_goTypes,
		DependencyIndexes: file_proto_product_proto_depIdxs,
		MessageInfos:      file_proto_product_proto_msgTypes,
	}.Build()
	File_proto_product_proto = out.File
	file_proto_product_proto_goTypes = nil
	file_proto_product_proto_depIdxs = nil
}
