// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: product.proto

package server

import (
	"context"

	"github.com/292292yang/go-zero-mall/product-rpc/internal/logic"
	"github.com/292292yang/go-zero-mall/product-rpc/internal/svc"
	"github.com/292292yang/go-zero-mall/product-rpc/product"
)

type ProductServer struct {
	svcCtx *svc.ServiceContext
	product.UnimplementedProductServer
}

func NewProductServer(svcCtx *svc.ServiceContext) *ProductServer {
	return &ProductServer{
		svcCtx: svcCtx,
	}
}

func (s *ProductServer) CreateProduct(ctx context.Context, in *product.CreateProductReq) (*product.CreateProductResp, error) {
	l := logic.NewCreateProductLogic(ctx, s.svcCtx)
	return l.CreateProduct(in)
}

func (s *ProductServer) GetProduct(ctx context.Context, in *product.GetProductReq) (*product.GetProductResp, error) {
	l := logic.NewGetProductLogic(ctx, s.svcCtx)
	return l.GetProduct(in)
}

func (s *ProductServer) ListProduct(ctx context.Context, in *product.ListProductReq) (*product.ListProductResp, error) {
	l := logic.NewListProductLogic(ctx, s.svcCtx)
	return l.ListProduct(in)
}

func (s *ProductServer) CheckStock(ctx context.Context, in *product.CheckStockReq) (*product.CheckStockResp, error) {
	l := logic.NewCheckStockLogic(ctx, s.svcCtx)
	return l.CheckStock(in)
}

func (s *ProductServer) DeductStock(ctx context.Context, in *product.DeductStockReq) (*product.DeductStockResp, error) {
	l := logic.NewDeductStockLogic(ctx, s.svcCtx)
	return l.DeductStock(in)
}
